### ISSUE TITLE
JAASteensgaardRegionAware takes more than 5 minutes to compile 134 lines of code

### ISSUE THREAD

**Issue by sjalander** [phate/jlm#199]
jlc -JAASteensgaardRegionAware chomp.c

[chomp.tgz](https://github.com/phate/jlm/files/10978423/chomp.tgz)

**Comment by phate** [comment]
Minimal example that seems to trigger the behavior:

```
struct list
{
  struct list * next;
} * myList;

void
traverse()                    
{
  struct list * tmp = myList;
  while (tmp) {
    tmp = tmp->next;
  }
}
``` 

Compile with:
`jlc -JAASteensgaardRegionAware -O3 -c file.c`

The problem seems to originate from the [FindModuleEscapingMemoryNodes lambda](https://github.com/phate/jlm/blob/ad8d2e0d4006394d07f4522d722f3a59f41dd977/libjlm/src/opt/alias-analyses/Steensgaard.cpp#L1640). The program introduces a cycle in the LocationSet graph and this function does not really take care of cycles. I needs to break the cycles by keeping track of the visited nodes.

**Comment by phate** [comment]
An even smaller example that exposes the problem is:

```
struct list 
{
  struct list * next;
} * myList;

struct list *
next()
{
  struct list * tmp = myList;
  tmp = tmp->next;
  return tmp;
}
```
Compile with:
`jlc- -JAASteensgaardRegionAware -c file.c`
