### ISSUE TITLE
Programs with loads from NULL have undefined behavior, but jlm shouldn't crash while compiling them

### ISSUE THREAD

**Issue by haved** [phate/jlm#331]
Related to #323.

Take the following C program:
```c
static int *refarr;

int
main()
{
    return *refarr;
}
```
This program is not well-formed.
Since `refarr` is static, it will always be `NULL`, and clang knows this.
The produced LLVM IR with -O0 is

<details>
<summary>Click to expand</summary>

```llvm
@refarr = internal global ptr null, align 8

define dso_local i32 @main() {
  %1 = alloca i32, align 4
  store i32 0, ptr %1, align 4
  %2 = load ptr, ptr @refarr, align 8
  %3 = load i32, ptr %2, align 4
  ret i32 %3
}
```
</details>

As can be seen, clang makes up an `alloca` instruction in `main()`, stores 0 to it, and never reads from it.
Compilers are of course allowed to do whatever they like with ill-formed programs, so we can't fault it.

By applying `jlm-opt --AAAndersenAgnostic`, the following RVSDG is produced:
![image](https://github.com/phate/jlm/assets/3748845/8ebd735f-8bce-403b-8b8a-4e409c8a9906)

The alias analysis correctly figures out that the last load, the load from `refarr`, can't point to anything, which means the load doesn't depend on any memory state. This leads to a load node with a single operand, which is illegal in the `jlm::llvm::is_load_mux_reducible` function.

My question is: should we give loads and stores affecting 0 memory states a dummy memory state edge input, or allow them to have zero memory state edge inputs? (A well-formed program should never have loads or stores like that, but we should at least gracefully handle ill-formed programs, and not just crash).

**Comment by phate** [comment]
Thanks for the clear write-up.

If it is 'illegal' in the `jlm::llvm::is_load_mux` reduction, then the bug is there. It should be able to handle load nodes with no state. Such loads and stores make sense, considering that they actually do not touch any memory. These reductions were implemented before the entire memory encoding story came along. The memory state encoding changed the semantic/structure of some operations (e.g., load nodes without state, which was 'not possible' before), but the reductions were not adjusted accordingly (since I did not know where this entire story will go in the first place).

I will attend to it and fix the issue. We have massive problems with (some of) the node reductions anyway, judging by the amount of open issues. So an overhaul is overdue.
