### ISSUE TITLE
Documentation generation fails when CIRCT or MLIR dependency are compiled in JLM_ROOT

### ISSUE THREAD

**Issue by phate** [phate/jlm#405]
The `build-circt.sh` and `build-mlir.sh` scripts put the source for the external dependencies in the jlm root directory. When creating the doxygen documentation, these folder are picked up by doxygen as well, resulting in failing documentation generation.

**Comment by phate** [comment]
Doxygen has options for excluding certain directories from the documentation generation process.

**Comment by sjalander** [comment]
@phate Since the build scripts can be configured with any build path, we don't know where the source of MLIR and CIRCT will be placed. So wouldn't it be better to instead specify where the JLM source code is expected, as it is unlikely that people chose a path for building MLIR and CIRCT that's within the source code.
That would be to set 
INPUT = ./jlm ./tools

**Comment by phate** [comment]
Good point. Yes, this would be right way to go about this. Thanks!
